### ISSUE TITLE
non-important ISSUE!!!

### ISSUE THREAD

**Issue by JOEMAMA676** [SomeRandomGitGuy/Tria-Magicis#5]
NO GUNS!!! NO BLOOD!!! ME SAD!!!

**Comment by Slimey676** [comment]
Ummmm… I don’t think there should be blood….

**Comment by JOEMAMA676** [comment]
NOOOOOOOOOOOOOOO!!! BLOOD = MORE VIEWS!!!

**Comment by SomeRandomCrazyGuy** [comment]
Yes, more views along with dislikes. This isn't a Mature 17+ game.

**Comment by SomeRandomGitGuy** [comment]
@Slimey676 @JOEMAMA676 @SomeRandomCrazyGuy so are you all the same person?

**Comment by SomeRandomGitGuy** [comment]
please do not open issues for no reason. This is not an issue. this is a suggestion by you. so put it in discussions. And do not clone accounts please. I can even see how many clones are visiting this page btw

**Comment by SomeRandomCrazyGuy** [comment]
no
